spring:
  config:
    activate:
      on-profile: postprod
  datasource:
    url: jdbc:oracle:thin:@//postprod-host:1521/POSTPRODDB
    username: postprod_user
    password: postprod_password
    driver-class-name: oracle.jdbc.OracleDriver
