spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:oracle:thin:@//prod-host:1521/PRODDB
    username: prod_user
    password: prod_password
    driver-class-name: oracle.jdbc.OracleDriver

app:
  loader:
    scheduler:
      # Midnight daily
      cron: "0 0 0 * * *"
    input-directory: lms/files/input
    success-directory: lms/files/success
    failed-directory: lms/files/failed
    input-charset: UTF-8
    batch-size: 500
    files:
      - file-name: CLFACV.TXT
        data-source: primary
        table-name: STG_HK_OBS_FACVDW
        columns:
          - name: BNK_NO
            length: 3
          - name: CUST_ACCT_NO
            length: 12
          - name: SYS_COD
            length: 3
          - name: REC_TYPE
            length: 1
          - name: CUST_GP
            length: 1
          - name: ITL_CUST_NO
            length: 11
          - name: FILLER
            length: 11
          - name: LMT_ID
            length: 5
          - name: CUST_ID
            length: 11
          - name: FILLER1
            length: 7
          - name: MAINT_ACT
            length: 1
      - file-name: CLFACVHASE.TXT
        data-source: primary
        table-name: STG_HK_OBS_FACVDW
        columns:
          - name: BNK_NO
            length: 3
          - name: CUST_ACCT_NO
            length: 12
          - name: SYS_COD
            length: 3
          - name: REC_TYPE
            length: 1
          - name: CUST_GP
            length: 1
          - name: ITL_CUST_NO
            length: 11
          - name: FILLER
            length: 11
          - name: LMT_ID
            length: 5
          - name: CUST_ID
            length: 11
          - name: FILLER1
            length: 7
          - name: MAINT_ACT
            length: 1
