ALTER TABLE STG_HK_OBS_FACVDW ADD (BNK_NO_TXT VARCHAR2(3 CHAR));

UPDATE STG_HK_OBS_FACVDW
SET BNK_NO_TXT = LPAD(TO_CHAR(BNK_NO), 3, '0');

ALTER TABLE STG_HK_OBS_FACVDW DROP COLUMN BNK_NO;

ALTER TABLE STG_HK_OBS_FACVDW RENAME COLUMN BNK_NO_TXT TO BNK_NO;

ALTER TABLE STG_HK_OBS_FACVDW MODIFY (BNK_NO VARCHAR2(3 CHAR) NOT NULL);
