CREATE TABLE STG_HK_OBS_IMTM (
    STG_KEY      NUMBER NOT NULL,
    TREE_ID                   VARCHAR2(24 CHAR),
    LMT_ID                    VARCHAR2(5 CHAR),
    MAINT_ACT                 VARCHAR2(1 CHAR),
    MAX_BP_BD_TERM            VARCHAR2(4 CHAR),
    MAX_PC_TERM               VARCHAR2(4 CHAR),
    MAX_PC_CR                 VARCHAR2(4 CHAR),
    NT_STD_INT_RT_FLG         VARCHAR2(10 CHAR),
    INT_BOOK_REC              VARCHAR2(30 CHAR),
    NT_STD_COMM_FLG           VARCHAR2(1 CHAR),
    REMK_FULL                 VARCHAR2(400 CHAR),
    CILE_CCY                  VARCHAR2(3 CHAR),
    CILE_MIN_AMT_SIGN         VARCHAR2(1 CHAR),
    CILE_MIN_AMT_VALUE        VARCHAR2(11 CHAR),
    CILE_MIN_AMT_DCML         VARCHAR2(1 CHAR),
    CILE_TIER_AMT_1_SIGN      VARCHAR2(1 CHAR),
    CILE_TIER_AMT_1_VALUE     VARCHAR2(11 CHAR),
    CILE_TIER_AMT_1_DCML      VARCHAR2(1 CHAR),
    CILE_TIER_AMT_2_SIGN      VARCHAR2(1 CHAR),
    CILE_TIER_AMT_2_VALUE     VARCHAR2(11 CHAR),
    CILE_TIER_AMT_2_DCML      VARCHAR2(1 CHAR),
    CILE_TIER_AMT_3_SIGN      VARCHAR2(1 CHAR),
    CILE_TIER_AMT_3_VALUE     VARCHAR2(11 CHAR),
    CILE_TIER_AMT_3_DCML      VARCHAR2(1 CHAR),
    CILE_TIER_AMT_4_SIGN      VARCHAR2(1 CHAR),
    CILE_TIER_AMT_4_VALUE     VARCHAR2(11 CHAR),
    CILE_TIER_AMT_4_DCML      VARCHAR2(1 CHAR),
    CILE_TIER_AMT_5_SIGN      VARCHAR2(1 CHAR),
    CILE_TIER_AMT_5_VALUE     VARCHAR2(11 CHAR),
    CILE_TIER_AMT_5_DCML      VARCHAR2(1 CHAR),
    CILE_TIER_RT_1_SIGN       VARCHAR2(1 CHAR),
    CILE_TIER_RT_1_VALUE      VARCHAR2(11 CHAR),
    CILE_TIER_RT_1_DCML       VARCHAR2(1 CHAR),
    CILE_TIER_RT_2_SIGN       VARCHAR2(1 CHAR),
    CILE_TIER_RT_2_VALUE      VARCHAR2(11 CHAR),
    CILE_TIER_RT_2_DCML       VARCHAR2(1 CHAR),
    CILE_TIER_RT_3_SIGN       VARCHAR2(1 CHAR),
    CILE_TIER_RT_3_VALUE      VARCHAR2(11 CHAR),
    CILE_TIER_RT_3_DCML       VARCHAR2(1 CHAR),
    CILE_TIER_RT_4_SIGN       VARCHAR2(1 CHAR),
    CILE_TIER_RT_4_VALUE      VARCHAR2(11 CHAR),
    CILE_TIER_RT_4_DCML       VARCHAR2(1 CHAR),
    CILE_TIER_RT_5_SIGN       VARCHAR2(1 CHAR),
    CILE_TIER_RT_5_VALUE      VARCHAR2(11 CHAR),
    CILE_TIER_RT_5_DCML       VARCHAR2(1 CHAR),
    CILE_TIER_RT_6_SIGN       VARCHAR2(1 CHAR),
    CILE_TIER_RT_6_VALUE      VARCHAR2(11 CHAR),
    CILE_TIER_RT_6_DCML       VARCHAR2(1 CHAR),
    CHRG_COMM_REC_1           VARCHAR2(149 CHAR),
    FINC_RT_1_SIGN            VARCHAR2(1 CHAR),
    FINC_RT_1_VALUE           VARCHAR2(11 CHAR),
    FINC_RT_1_DCML            VARCHAR2(1 CHAR),
    FINC_RT_2_SIGN            VARCHAR2(1 CHAR),
    FINC_RT_2_VALUE           VARCHAR2(11 CHAR),
    FINC_RT_2_DCML            VARCHAR2(1 CHAR),
    FINC_RT_3_SIGN            VARCHAR2(1 CHAR),
    FINC_RT_3_VALUE           VARCHAR2(11 CHAR),
    FINC_RT_3_DCML            VARCHAR2(1 CHAR),
    FINC_RT_4_SIGN            VARCHAR2(1 CHAR),
    FINC_RT_4_VALUE           VARCHAR2(11 CHAR),
    FINC_RT_4_DCML            VARCHAR2(1 CHAR),
    FINC_PR_1_SIGN            VARCHAR2(1 CHAR),
    FINC_PR_1_VALUE           VARCHAR2(3 CHAR),
    FINC_PR_2_SIGN            VARCHAR2(1 CHAR),
    FINC_PR_2_VALUE           VARCHAR2(3 CHAR),
    FINC_PR_3_SIGN            VARCHAR2(1 CHAR),
    FINC_PR_3_VALUE           VARCHAR2(3 CHAR),
    FINC_PR_4_SIGN            VARCHAR2(1 CHAR),
    FINC_PR_4_VALUE           VARCHAR2(3 CHAR),
    FINC_AMT_1_SIGN           VARCHAR2(1 CHAR),
    FINC_AMT_1_VALUE          VARCHAR2(11 CHAR),
    FINC_AMT_1_DCML           VARCHAR2(1 CHAR),
    FINC_AMT_2_SIGN           VARCHAR2(1 CHAR),
    FINC_AMT_2_VALUE          VARCHAR2(11 CHAR),
    FINC_AMT_2_DCML           VARCHAR2(1 CHAR),
    FINC_AMT_3_SIGN           VARCHAR2(1 CHAR),
    FINC_AMT_3_VALUE          VARCHAR2(11 CHAR),
    FINC_AMT_3_DCML           VARCHAR2(1 CHAR),
    FINC_AMT_4_SIGN           VARCHAR2(1 CHAR),
    FINC_AMT_4_VALUE          VARCHAR2(11 CHAR),
    FINC_AMT_4_DCML           VARCHAR2(1 CHAR),
    FINC_CCY_UPR_LWR_LMT      VARCHAR2(3 CHAR),
    FINC_UPR_LMT_SIGN         VARCHAR2(1 CHAR),
    FINC_UPR_LMT_VALUE        VARCHAR2(11 CHAR),
    FINC_UPR_LMT_DCML         VARCHAR2(1 CHAR),
    FINC_LWR_LMT_SIGN         VARCHAR2(1 CHAR),
    FINC_LWR_LMT_VALUE        VARCHAR2(11 CHAR),
    FINC_LWR_LMT_DCML         VARCHAR2(1 CHAR),
    CLLTN_RT_1_SIGN           VARCHAR2(1 CHAR),
    CLLTN_RT_1_VALUE          VARCHAR2(11 CHAR),
    CLLTN_RT_1_DCML           VARCHAR2(1 CHAR),
    CLLTN_RT_2_SIGN           VARCHAR2(1 CHAR),
    CLLTN_RT_2_VALUE          VARCHAR2(11 CHAR),
    CLLTN_RT_2_DCML           VARCHAR2(1 CHAR),
    CLLTN_RT_3_SIGN           VARCHAR2(1 CHAR),
    CLLTN_RT_3_VALUE          VARCHAR2(11 CHAR),
    CLLTN_RT_3_DCML           VARCHAR2(1 CHAR),
    CLLTN_RT_4_SIGN           VARCHAR2(1 CHAR),
    CLLTN_RT_4_VALUE          VARCHAR2(11 CHAR),
    CLLTN_RT_4_DCML           VARCHAR2(1 CHAR),
    CLLTN_PR_1_SIGN           VARCHAR2(1 CHAR),
    CLLTN_PR_1_VALUE          VARCHAR2(3 CHAR),
    CLLTN_PR_2_SIGN           VARCHAR2(1 CHAR),
    CLLTN_PR_2_VALUE          VARCHAR2(3 CHAR),
    CLLTN_PR_3_SIGN           VARCHAR2(1 CHAR),
    CLLTN_PR_3_VALUE          VARCHAR2(3 CHAR),
    CLLTN_PR_4_SIGN           VARCHAR2(1 CHAR),
    CLLTN_PR_4_VALUE          VARCHAR2(3 CHAR),
    CLLTN_AMT_1_SIGN          VARCHAR2(1 CHAR),
    CLLTN_AMT_1_VALUE         VARCHAR2(11 CHAR),
    CLLTN_AMT_1_DCML          VARCHAR2(1 CHAR),
    CLLTN_AMT_2_SIGN          VARCHAR2(1 CHAR),
    CLLTN_AMT_2_VALUE         VARCHAR2(11 CHAR),
    CLLTN_AMT_2_DCML          VARCHAR2(1 CHAR),
    CLLTN_AMT_3_SIGN          VARCHAR2(1 CHAR),
    CLLTN_AMT_3_VALUE         VARCHAR2(11 CHAR),
    CLLTN_AMT_3_DCML          VARCHAR2(1 CHAR),
    CLLTN_AMT_4_SIGN          VARCHAR2(1 CHAR),
    CLLTN_AMT_4_VALUE         VARCHAR2(11 CHAR),
    CLLTN_AMT_4_DCML          VARCHAR2(1 CHAR),
    CLLTN_CCY_UPR_LWR_LMT     VARCHAR2(3 CHAR),
    CLLTN_UPR_LMT_SIGN        VARCHAR2(1 CHAR),
    CLLTN_UPR_LMT_VALUE       VARCHAR2(11 CHAR),
    CLLTN_UPR_LMT_DCML        VARCHAR2(1 CHAR),
    CLLTN_LWR_LMT_SIGN        VARCHAR2(1 CHAR),
    CLLTN_LWR_LMT_VALUE       VARCHAR2(11 CHAR),
    CLLTN_LWR_LMT_DCML        VARCHAR2(1 CHAR),
    CHRG_COMM_REC_2           VARCHAR2(298 CHAR),
    REGION       VARCHAR2(6 CHAR),
    BATCH_RUN_ID NUMBER NOT NULL,
    CRTD_DT_TM   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CRTD_BY      VARCHAR2(100 CHAR) DEFAULT 'CLFACV_LOADER' NOT NULL,
    MOD_DT_TM    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    MOD_BY       VARCHAR2(100 CHAR) DEFAULT 'CLFACV_LOADER' NOT NULL,
    CONSTRAINT PK_STG_HK_OBS_IMTM PRIMARY KEY (STG_KEY)
);

CREATE SEQUENCE STG_HK_OBS_IMTM_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER BI_STG_HK_OBS_IMTM
BEFORE INSERT ON STG_HK_OBS_IMTM
FOR EACH ROW
BEGIN
    IF :NEW.STG_KEY IS NULL THEN
        SELECT STG_HK_OBS_IMTM_SEQ.NEXTVAL INTO :NEW.STG_KEY FROM DUAL;
    END IF;

    IF :NEW.CRTD_DT_TM IS NULL THEN
        :NEW.CRTD_DT_TM := SYSTIMESTAMP;
    END IF;

    IF :NEW.CRTD_BY IS NULL THEN
        :NEW.CRTD_BY := 'CLFACV_LOADER';
    END IF;

    IF :NEW.MOD_DT_TM IS NULL THEN
        :NEW.MOD_DT_TM := SYSTIMESTAMP;
    END IF;

    IF :NEW.MOD_BY IS NULL THEN
        :NEW.MOD_BY := 'CLFACV_LOADER';
    END IF;
END;
/
