spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:oracle:thin:@//prod-host:1521/PRODDB
    username: prod_user
    password: prod_password
    driver-class-name: oracle.jdbc.OracleDriver

app:
  scheduler:
    # Midnight daily
    cron: "0 0 0 * * *"
  loader:
    input-directory: lms/files/input
    success-directory: lms/files/success
    failed-directory: lms/files/failed
