spring:
  config:
    activate:
      on-profile: postprod
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: system
    password: System@123
    driver-class-name: oracle.jdbc.OracleDriver

app:
  loader:
    scheduler:
      # Test schedule (change as needed)
      cron: "0 0/2 * * * *"
    input-directory: ${user.home}/Documents/hub/var/incoming
    success-directory: ${user.home}/Documents/hub/var/success
    failed-directory: ${user.home}/Documents/hub/var/failed
    input-charset: UTF-8
    batch-size: 500
    files:
      - file-name: CLFACV.TXT
        data-source: primary
        table-name: STG_HK_OBS_FACVDW
      - file-name: CLFACVHASE.TXT
        data-source: primary
        table-name: STG_HK_OBS_FACVDW
      - file-name: CLIMTM.TXT
        data-source: primary
        table-name: STG_HK_OBS_IMTM
